### PR TITLE
Update build script to display a link that opens the resulting built book

### PR DESCRIPTION
**Pull request by sgilda**
@stianst : your updates look great to me and definitely simplify things. This update just allows you to click on the resulting link in the terminal to view the built book.

One other suggestion would be to define all of the book titles in the JSON files and use those rather than hard-code them in SUMMARY.adoc each book. That way, all external references to the book will match, and if a book title needs to change, you can do it in the one place.

### CODE REVIEW

**Comment by stianst** [comment]
I don't actually think the title in the summary files is used at all. It's not in community at least.

**Comment by sgilda** [comment]
@stianst : That's odd, because any links between books should probably use the same title that's used for the SUMMARY.adoc file. I'll check with @jmalloy.

**Comment by stianst** [comment]
Links between guides use the links:
https://github.com/stianst/keycloak-documentation/blob/SINGLE-SCRIPTS/book-product.json#L32

**Comment by sgilda** [comment]
@stianst : In that case, those same variables should be used in the SUMMARY.adoc files. For example, the getting_started/SUMMARY.adoc file should have {{book_gettingstarted_name}} and the name variable should probably be defined as "Getting Started Guide" instead of "Getting Started Tutorial". For example:

  "gettingstarted": {
      "name": "Getting Started Guide",
      "link": "https://access.redhat.com/documentation/en/red-hat-single-sign-on/SNAPSHOT/html/getting-started-guide/"
    },

Where there are links to other books, the book titles should match what is define in the title for that book.

@jmalloy, WDYT?

**Comment by stianst** [comment]
I thought the titles on the summary pages wasn't used, but just checked and it's used as the title in product guides.

+1 To using {{book_gettingstarted_name}}

**Pull request merged**
